# Generated by Django 5.2.15 on 2026-06-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='reference',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('ltc', 'Litecoin'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('internal', 'Internal')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('investment', 'Investment'), ('return', 'Investment Return'), ('purchase', 'Vehicle Purchase')], max_length=20),
        ),
    ]
