# Generated by Django 5.2.15 on 2026-06-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_wallettransaction_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='destination',
            field=models.TextField(blank=True, default=''),
        ),
    ]
