# Generated by Django 5.2.15 on 2026-06-16 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wallettransaction_destination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentplan',
            options={'ordering': ['roi_percent']},
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='amount_per_cycle',
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='next_execution',
        ),
        migrations.RemoveField(
            model_name='investmentplan',
            name='profile',
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='badge_color',
            field=models.CharField(default='gray', max_length=30),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=14),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='roi_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='cycle',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20),
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('matures_at', models.DateTimeField()),
                ('paid_out_at', models.DateTimeField(blank=True, null=True)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.investmentplan')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_investments', to='core.profile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
