# Generated by Django 5.2.15 on 2026-06-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_investmentplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='cycle',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('bi-annually', 'Bi-Anually'), ('annually', 'Anually')], default='monthly', max_length=20),
        ),
    ]
