# Generated by Django 5.2.15 on 2026-06-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_investmentplan_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('investment', 'Investment'), ('return', 'Investment Return'), ('purchase', 'Vehicle Purchase'), ('stock_buy', 'Stock Purchase'), ('stock_sell', 'Stock Sale')], max_length=20),
        ),
    ]
