# Generated by Django 5.2.15 on 2026-06-20 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='id_back',
        ),
        migrations.AddField(
            model_name='kycverification',
            name='address_type',
            field=models.CharField(blank=True, choices=[('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('rental_agreement', 'Rental Agreement')], max_length=50),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='passport_image',
            field=models.ImageField(blank=True, upload_to='kyc/passports/'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='proof_of_address',
            field=models.ImageField(blank=True, upload_to='kyc/address/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('drivers_license', 'Driver’s License')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
