# Generated by Django 5.2.15 on 2026-06-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_kycverification_id_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kyc_tier',
            field=models.CharField(choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3')], default='tier1', max_length=20),
        ),
    ]
