# Generated by Django 5.2.15 on 2026-06-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profile_kyc_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='previous_kyc_status',
            field=models.CharField(blank=True, choices=[('not_submitted', 'Not Submitted'), ('pending', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_kyc_tier',
            field=models.CharField(blank=True, choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kyc_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kyc_tier',
            field=models.CharField(choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3')], default='tier1', max_length=10),
        ),
    ]
