# Generated by Django 5.2.15 on 2026-06-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='id_back',
            field=models.ImageField(blank=True, upload_to='kyc/ids/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('drivers_license', "Driver's License")], max_length=50),
        ),
    ]
