# Generated by Django 5.2.15 on 2026-06-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_kycverification_id_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='id_back',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='id_front',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='id_type',
        ),
        migrations.AddField(
            model_name='kycverification',
            name='drivers_license_back',
            field=models.ImageField(blank=True, upload_to='kyc/drivers_license/'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='drivers_license_front',
            field=models.ImageField(blank=True, upload_to='kyc/drivers_license/'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='drivers_license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='national_id_back',
            field=models.ImageField(blank=True, upload_to='kyc/national_id/'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='national_id_front',
            field=models.ImageField(blank=True, upload_to='kyc/national_id/'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
