# Generated by Django 5.2.15 on 2026-06-23 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_kycverification_id_back_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='drivers_license_back',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='drivers_license_front',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='drivers_license_number',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='national_id_back',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='national_id_front',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='national_id_number',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='passport_image',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='passport_number',
        ),
        migrations.AddField(
            model_name='kycverification',
            name='id_back',
            field=models.ImageField(blank=True, upload_to='kyc/ids/'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='id_front',
            field=models.ImageField(blank=True, upload_to='kyc/ids/'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID Card'), ('drivers_license', "Driver's License"), ('passport', 'Passport'), ('residence_permit', 'Residence Permit')], max_length=30),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='address_type',
            field=models.CharField(blank=True, choices=[('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('rental_agreement', 'Rental Agreement'), ('government_letter', 'Government Letter')], max_length=30),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
