# Generated by Django 5.2.15 on 2026-06-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_kycverification_drivers_license_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='kyc_tier',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='previous_kyc_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='previous_kyc_tier',
        ),
    ]
