# Generated by Django 5.2.15 on 2026-06-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_profile_kyc_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID Card'), ('drivers_license', "Driver's License")], max_length=30),
        ),
    ]
