# Generated by Django 5.2.15 on 2026-06-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_avatar_alter_kycverification_id_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=10)),
                ('network_label', models.CharField(blank=True, max_length=60)),
                ('network_key', models.CharField(choices=[('btc', 'Bitcoin (BTC)'), ('eth', 'Ethereum (ETH)'), ('ltc', 'Litecoin (LTC)'), ('usdt', 'Tether (USDT)'), ('usdc', 'USD Coin (USDC)'), ('bnb', 'BNB (BEP-20)'), ('sol', 'Solana (SOL)'), ('trx', 'TRON (TRX)'), ('xrp', 'Ripple (XRP)'), ('doge', 'Dogecoin (DOGE)'), ('other', 'Other')], default='other', max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('color', models.CharField(default='bg-gray-500', max_length=40)),
                ('icon_symbol', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
