# Generated by Django 5.2.15 on 2026-06-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='network_key',
            field=models.CharField(choices=[('btc', 'Bitcoin (BTC)'), ('eth', 'Ethereum (ERC-20)'), ('ltc', 'Litecoin (LTC)'), ('usdt', 'Tether (USDT)'), ('usdc', 'USD Coin (USDC)'), ('bnb', 'BNB Smart Chain (BEP-20)'), ('sol', 'Solana (SOL)'), ('trx', 'Tron (TRC-20)'), ('xrp', 'Ripple (XRP)'), ('doge', 'Dogecoin (DOGE)'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
