# Generated by Django 5.2.15 on 2026-06-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_deposit_method',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_withdrawal_method',
            field=models.BooleanField(default=True),
        ),
    ]
