# Generated by Django 5.2.15 on 2026-06-29 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_paymentmethod_is_deposit_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='network_key',
            field=models.CharField(choices=[('btc', 'Bitcoin (BTC)'), ('eth', 'Ethereum (ERC-20)'), ('ltc', 'Litecoin (LTC)'), ('usdt', 'Tether (USDT)'), ('usdc', 'USD Coin (USDC)'), ('bnb', 'BNB Smart Chain (BEP-20)'), ('sol', 'Solana (SOL)'), ('trx', 'Tron (TRC-20)'), ('xrp', 'Ripple (XRP)'), ('doge', 'Dogecoin (DOGE)'), ('bank', 'Bank'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=8, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_access_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
