from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.decorators.http import require_POST
from .views import deposit_confirm_view, index, home, blog, investments_view, investment_subscribe, login, profile_view, register, dashboard, kyc_view, stock_confirm, wallet_view, deposit_view, withdraw_view, withdraw_confirm_view, stocks_list, stock_detail, stock_buy, portfolio_view, inventory_view, vehicle_detail_view, vehicle_order_view, vehicle_order_confirm_view, vehicle_order_success_view, logout, orders_view, notifications_view, mark_all_notifications_read, notifications_unread_count, mark_notification_read, about, careers, help, privacy, terms, verify_email, settings_view, password_reset_confirm, password_reset_done, password_reset_request, security_view, change_password_view, two_factor_view, access_code_view

urlpatterns = [
    path('', index, name='index'),
    path('home/', home, name='home'),
    path('validate/', access_code_view, name='access_code'),
    path('blog/', blog, name='blog'),
    path('about/', about, name='about'),
    path('careers/', careers, name='careers'),
    path('help/', help, name='help'),
    path('privacy/', privacy, name='privacy'),
    path('terms/', terms, name='terms'),
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('verify-email/', verify_email, name='verify_email'),
    path('logout/', logout, name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
    path('settings/', settings_view, name='settings'),
    path('profile/', profile_view, name='profile'),
    path('kyc/', kyc_view, name='kyc'),
    path('security/', security_view, name='security'),
    path('security/change-password/', change_password_view, name='change_password'),
    path('security/two-factor/', two_factor_view, name='two_factor'),

    
    path('wallet/', wallet_view, name='wallet'),
    path('deposit/', deposit_view, name='deposit'),
    path('deposit/<int:pk>/confirm/', deposit_confirm_view, name='deposit_confirm'),
    path('withdraw/', withdraw_view, name='withdraw'),
    path('withdraw/<int:pk>/confirm/', withdraw_confirm_view, name='withdraw_confirm'),
    path('stocks/', stocks_list, name='stocks'),
    path('stocks/<str:symbol>/', stock_detail, name='stock_detail'),
    path('stocks/<str:symbol>/buy/', stock_buy, name='stock_buy'),
    path('stocks/<str:symbol>/confirm/', stock_confirm, name='stock_confirm'),
    path('investments/', investments_view, name='investments'),
    path('investments/subscribe/<int:plan_id>/', investment_subscribe, name='investment_subscribe'),
    path('portfolio/', portfolio_view, name='portfolio'),
    path('inventory/', inventory_view, name='inventory'),
    path('inventory/<int:pk>/', vehicle_detail_view, name='vehicle_detail'),
    path('inventory/<int:pk>/order/', vehicle_order_view, name='vehicle_order'),
    path('inventory/<int:pk>/order/confirm/', vehicle_order_confirm_view, name='vehicle_order_confirm'),
    path('inventory/<int:pk>/order/success/', vehicle_order_success_view, name='vehicle_order_success'),
    path('orders/', orders_view, name='orders'),
    path('notifications/', notifications_view, name='notifications'),
    path('notifications/<int:pk>/read/', mark_notification_read, name='notification_read'),
    path('notifications/read-all/', mark_all_notifications_read, name='notifications_read_all'),
    path('notifications/count/', notifications_unread_count, name='notifications_count'),

    path('password-reset/', password_reset_request, name='password_reset'),
    path('password-reset/done/', password_reset_done, name='password_reset_done'),
    path('password-reset-confirm/<uuid:token>/', password_reset_confirm, name='password_reset_confirm'),
]